var data = "<script charset='utf-8' src='http:\/\/widgets.twimg.com\/j\/2\/widget.js'><\/script>"
+"<script>"
+"new TWTR.Widget({"
+"  version: 2,"
+"  type: 'search',"
+"  search: 'rainbow',"
+"  interval: 30000,"
+"  title: 'Its a double rainbow',"
+"  subject: 'Across the sky',"
+"  width: 250,"
+"  height: 300,"
+"  theme: {"
+"    shell: {"
+"      background: '#8ec1da',"
+"      color: '#ffffff'"
+"    },"
+"    tweets: {"
+"      background: '#ffffff',"
+"      color: '#444444',"
+"      links: '#1985b5'"
+"    }"
+"  },"
+"  features: {"
+"    scrollbar: false,"
+"    loop: true,"
+"    live: true,"
+"    behavior: 'default'"
+"  }"
+"}).render().start();"
+"<\/script>";
document.getElementById('liveTweets').innerHTML = eval(data);
